import React, { useEffect, useRef, useState } from 'react'
import { getLocalItem, removeItem, setLocalItem } from '../../utils/Storage'
import {
  Box,
  Stack,
  TextareaAutosize,
  ThemeProvider,
  Typography,
} from '@mui/material'
import { v4 as uuidv4 } from 'uuid'
import send_icon from '../../assets/Images/Icons/send.svg'
import { aiCalls } from '../../api/aiCalls.api'
import CCMultilineTextArea from '../../atoms/CCMultilineTextArea'
import useClickOutside from '../../hooks/useClickOutside'
import { useAppDispatch, useAppSelector } from '../../hooks/reduxHooks'
import { setProjectDescription } from '../../redux/Slices/CreateNewProject/draftPDDCompilationV2Slice'
import {
  setEditorBlockAction,
  setEditorBlockActionDeleteParams,
  setEditorBlockActionInsertParams,
  setEditorBlockActionUpdateParams,
} from '../../redux/Slices/GenerateAiSlice'
import './dynamicPostion.css'
import { addEllipses } from './helpers'

const DynamicPositionedAiComp = ({
  aiFieldText,
  closeComponent,
  showAIInputField,
  setAskAiTopPosition,
  setAiFieldText,
}: any) => {
  const dispatch = useAppDispatch()
  const aiInputRef: any = useRef(null)

  const [AIQuestion, setAIQuestion] = useState<any>('')
  const [AILoader, setAiLoader] = useState<any>(null)
  const [showOptionsBeforeAiRes, setShowOptionsBeforeAiRes] =
    useState<any>(true)
  const [showOptionsAfterAiRes, setShowOptionsAfterAiRes] = useState<any>(false)
  const [stopAiRes, setStopAiRes] = useState<any>(false)

  const [aiResponse, setAiResponse] = useState<any>('')
  const [placeholder, setPlaceHolder] = useState<string>('')
  const [previousRes, setPreviousRes] = useState<any>('')

  const [
    generativeAIBtnCreatedblockFilled,
    setGenerativeAIBtnCreatedblockFilled,
  ] = useState<any>(false)

  useClickOutside(aiInputRef, closeComponent)

  useEffect(() => {
    return () => {
      setAIQuestion('')
      setAiLoader(false)
      setShowOptionsBeforeAiRes(true)
      setShowOptionsAfterAiRes(false)
      setAiResponse('')
      //deleting the first block if block is generated by generate AI btn and when text is not entered.
      if (
        !generativeAIBtnCreatedblockFilled &&
        showAIInputField?.blockIndex === 0 &&
        showAIInputField?.generateAIBtnClicked
      ) {
        dispatch(
          setEditorBlockAction({
            modifyBlock: true,
            method: ['delete'],
          })
        )
        dispatch(setEditorBlockActionDeleteParams(0))
        setGenerativeAIBtnCreatedblockFilled(true)
      }
      setAiFieldText('')
      setAskAiTopPosition(null)
    }
  }, [])

  useEffect(() => {
    if (aiFieldText && !showAIInputField?.generateAIBtnClicked) {
      setPreviousRes(aiFieldText)
    }
  }, [aiFieldText])

  useEffect(() => {
    if (previousRes) {
      const ellipsesText = addEllipses(previousRes)
      setPlaceHolder(ellipsesText)
    }
  }, [previousRes])

  const generateAiUserId = () => {
    const id = uuidv4()
    setLocalItem('AI_user_id', id)
    return id
  }

  const sendPropmtToAi = async (
    event: any,
    improveWriting = '',
    fixGrammer = ''
  ) => {
    event.stopPropagation()
    try {
      setAiResponse('')
      //stopAiRes && setStopAiRes(false)
      setAiLoader(true)
      setShowOptionsBeforeAiRes(true)
      setShowOptionsAfterAiRes(false)
      const getUserId = getLocalItem('AI_user_id')
      const user_id = getUserId ? getUserId : generateAiUserId()

      const payload = {
        user_id: user_id,
        query:
          previousRes + AIQuestion + ' ' + improveWriting + ' ' + fixGrammer,
      }
      const res = await aiCalls.askAI(payload)
      if (res?.response) {
        console.log('is going inside the res')
        setPreviousRes(res?.response)
        setAiResponse(res?.response)
        setAIQuestion('')
        setShowOptionsBeforeAiRes(false)
        setShowOptionsAfterAiRes(true)
      }
    } catch (e) {
      console.log('error in getting ai prompt: ', e)
    } finally {
      setAiLoader(false)
    }
  }
  return (
    <Box ref={aiInputRef}>
      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          background: '#fff',
          width: '90%',
          boxShadow: '2px 2px 9px rgba(10, 10, 10, 0.2)',
          borderRadius: '6px',
          p: '14px 8px',
          m: '0px 10px 1px 10px',
        }}
      >
        <Box sx={{ px: 1 }}>
          {aiResponse && (
            <Typography sx={{ fontSize: '14px', fontWeight: '400', pb: 1 }}>
              {aiResponse}
            </Typography>
          )}
          <Box sx={{ display: 'flex' }}>
            <TextareaAutosize
              value={AIQuestion}
              minRows={3}
              maxRows={5}
              onChange={(e: any) => {
                //setStopAiRes(false)
                setAIQuestion(e.target.value)
              }}
              placeholder={placeholder + 'Enter your query here!'}
              style={{
                maxHeight: '200px',
                height: '80px',
                border: '1px solid rgba(0,0,0,0.1)',
                lineHeight: '1.3',
                width: '95%',
                outline: 'none',
                paddingLeft: '5px',
                overflow: 'scroll',
              }}
            />
            <Box sx={{ mt: 'auto' }}>
              {!AILoader ? (
                <Box
                  component={'img'}
                  src={send_icon}
                  onClick={(e: any) => sendPropmtToAi(e)}
                  sx={{ cursor: 'pointer', mt: 'auto', ml: 1 }}
                />
              ) : (
                <Stack
                  className=""
                  flexDirection={'column'}
                  alignItems={'center'}
                  gap={1}
                  sx={{ ml: 1 }}
                >
                  <Typography
                    className="option_when_generating_text_with_AI"
                    sx={{
                      color: '#2b846d',
                      fontWeight: '500',
                      fontSize: '14px',
                      cursor: 'pointer',
                    }}
                    onClick={(e: any) => {
                      e.stopPropagation()
                      //setAIQuestion('')
                      //setAiLoader(false)
                      //setStopAiRes(true)
                      //setShowOptionsBeforeAiRes(true)
                      //setShowOptionsAfterAiRes(false)
                    }}
                  >
                    Stop
                  </Typography>
                </Stack>
              )}
            </Box>
          </Box>
        </Box>
      </Box>
      {!AILoader && (
        <Box
          sx={{
            borderRadius: '6px',
            background: '#fff',
            boxShadow:
              'rgba(15, 15, 15, 0.05) 0px 0px 0px 1px, rgba(15, 15, 15, 0.1) 0px 3px 6px, rgba(15, 15, 15, 0.2) 0px 9px 24px',
            px: 1,
            maxWidth: '180px',
            width: '180px',
            zIndex: '9999999999',
            mt: 1,
            ml: '10px',
          }}
        >
          {showOptionsBeforeAiRes && !showAIInputField?.generateAIBtnClicked ? (
            <>
              <Typography
                textAlign="start"
                sx={{ fontSize: '12px', fontWeight: 500, pt: 1 }}
              >
                Edit or review selection
              </Typography>
              <Box
                sx={{
                  cursor: 'pointer',
                  //pb: 1,
                  borderRadius: 1,
                  py: 1,
                  '&:hover': {
                    backgroundColor: '#CCE8E1',
                  },
                }}
              >
                <Typography
                  onClick={(e: any) => {
                    sendPropmtToAi(e, 'improve writing')
                  }}
                  sx={{
                    fontSize: 14,
                    fontWeight: 500,
                    whiteSpace: 'nowrap',
                    color: '#01717F',
                  }}
                >
                  Improve writing
                </Typography>
              </Box>
              <Box
                sx={{
                  border: '1px solid rgba(0,0,0,0.3)',
                }}
              />
              <Box
                sx={{
                  cursor: 'pointer',
                  pb: 1,
                  borderRadius: 1,
                  pt: 1,
                  '&:hover': {
                    backgroundColor: '#CCE8E1',
                  },
                }}
              >
                <Typography
                  onClick={(e: any) => {
                    sendPropmtToAi(e, 'Fix Spelling and Grammer')
                  }}
                  sx={{
                    fontSize: 14,
                    fontWeight: 500,
                    whiteSpace: 'nowrap',
                    cursor: 'pointer',
                    color: '#01717F',
                  }}
                >
                  Fix Spelling & Grammer
                </Typography>
              </Box>
            </>
          ) : null}
          {showOptionsAfterAiRes ? (
            <>
              <Box
                sx={{
                  cursor: 'pointer',
                  borderRadius: 1,
                  py: 1,
                  '&:hover': {
                    backgroundColor: '#CCE8E1',
                  },
                }}
              >
                <Typography
                  onClick={(e) => {
                    e.stopPropagation()
                    if (showAIInputField?.generateAIBtnClicked) {
                      setGenerativeAIBtnCreatedblockFilled(true)
                    }
                    dispatch(
                      setEditorBlockAction({
                        modifyBlock: true,
                        method: ['update'],
                      })
                    )

                    dispatch(
                      setEditorBlockActionUpdateParams({
                        blockIndex: showAIInputField?.generateAIBtnClicked
                          ? 0
                          : parseInt(showAIInputField?.blockIndex),
                        data: {
                          text: aiResponse,
                        },
                      })
                    )
                    closeComponent()
                  }}
                  sx={{
                    fontSize: 14,
                    fontWeight: 500,
                    whiteSpace: 'nowrap',
                    pl: '4px',
                    color: '#01717F',
                  }}
                >
                  Replace Selection
                </Typography>
              </Box>
              {!showAIInputField?.generateAIBtnClicked && (
                <Box
                  sx={{
                    cursor: 'pointer',
                    borderRadius: 1,
                    py: 1,
                    '&:hover': {
                      backgroundColor: '#CCE8E1',
                    },
                  }}
                >
                  <Typography
                    onClick={() => {
                      dispatch(
                        setEditorBlockAction({
                          modifyBlock: true,
                          method: ['insert'],
                        })
                      )
                      dispatch(
                        setEditorBlockActionInsertParams({
                          type: 'paragraph',
                          data: { text: aiResponse },
                          config: null,
                          blockIndexToInsert:
                            parseInt(showAIInputField?.blockIndex) + 1,
                          focus: true,
                        })
                      )
                      closeComponent()
                    }}
                    sx={{
                      fontSize: 14,
                      fontWeight: 500,
                      whiteSpace: 'nowrap',
                      pl: '4px',
                      color: '#01717F',
                    }}
                  >
                    Insert Below
                  </Typography>
                </Box>
              )}
            </>
          ) : null}
        </Box>
      )}
    </Box>
  )
}

export default DynamicPositionedAiComp
