import { Box, Button, Menu, Typography } from '@mui/material'
import React, { FC, useState } from 'react'
import InfoOutlinedIcon from '@mui/icons-material/InfoOutlined'
import { Images } from '../../../../theme'
import { setLocalItem, setLocalItemForAi } from '../../../../utils/Storage'
import { useAppDispatch, useAppSelector } from '../../../../hooks/reduxHooks'
import {
  setEditorBlockAction,
  setEditorBlockActionInsertParams,
} from '../../../../redux/Slices/GenerateAiSlice'
import './infoText.css'
interface SubTitleProps {
  subTitle: string
  infoText: any
  showGenerateAIBtn?: boolean
}
const SubTitle: FC<SubTitleProps> = ({
  subTitle,
  infoText,
  showGenerateAIBtn = true,
}) => {
  const dispatch = useAppDispatch()

  // const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null)
  // const open = Boolean(anchorEl)
  const [open, setOpen] = useState(false)

  const handleClick = () => {
    // setAnchorEl(event.currentTarget)
    setOpen(!open)
  }

  const handleClose = () => {
    // setAnchorEl(null)
  }

  return (
    <>
      {' '}
      <Box
        sx={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
        }}
      >
        <Box sx={{ color: '#01717F', fontWeight: 500 }}>{subTitle}</Box>
        {showGenerateAIBtn && (
          <Box
            sx={{
              background: '#BED7FE',
              py: 1,
              px: 2,
              borderRadius: '24px',
              display: 'flex',
              alignItems: 'center',
              gap: 1,
              marginLeft: 'auto',
            }}
          >
            <Box component={'img'} src={Images.Generate_With_AI} />
            <Typography
              sx={{
                fontWeight: 500,
                fontSise: '14px',
                cursor: 'pointer',
                whiteSpace: 'nowrap',
              }}
              onClick={(e: any) => {
                e.stopPropagation()
                if (subTitle === '1.8 Chronological Plan Or Implementation') {
                  return
                }
                dispatch(
                  setEditorBlockAction({
                    modifyBlock: true,
                    method: ['insert'],
                  })
                )
                dispatch(
                  setEditorBlockActionInsertParams({
                    type: 'paragraph',
                    data: { text: 'This text here will be generated by AI.' },
                    config: null,
                    blockIndexToInsert: 0,
                    focus: true,
                  })
                )
                setLocalItemForAi('showAI', {
                  showAiField: true,
                  blockIndex: 0,
                  generateAIBtnClicked: true,
                })
              }}
            >
              Climat AI
            </Typography>
          </Box>
        )}
        <Box sx={{ z: 10 }}>
          <Button onClick={handleClick}>
            <InfoOutlinedIcon sx={{ color: '#029FB3' }} />
          </Button>
        </Box>
      </Box>
      <Box
        sx={{
          maxWidth: '600px',
          boxShadow: 'none',
          borderRadius: '8px',
          py: '16PX',
          px: '16px',
          background: '#DEEBFF',
          position: 'absolute',
          top: '140px',
          right: '70px',
          zIndex: 2,
          opacity: open ? 1 : 0,
          transform: open ? 'translateY(0)' : 'translateY(-20px)',
          transition:
            'transform 302ms cubic-bezier(0.4, 0, 0.2, 1), opacity 302ms cubic-bezier(0.4, 0, 0.2, 1)',
        }}
      >
        {infoText}
      </Box>
    </>
  )
}

export default SubTitle
